### PR TITLE
Add observers for local push notifications

### PR DESCRIPTION
**Pull request by slycoder**
This commit adds the delegate hooks so that local notifications get
passed onto the JS and adds a new event listener type for local
notifications.

### CODE REVIEW

**Comment by slycoder** [comment]
Thanks for the local push stuff, @jacobrosenthal .  I found it really useful so I decided to add some stuff I found helpful.

Your branch isn't in master yet so I thought I'd just put up this PR to get it on your radar first.

**Comment by jacobrosenthal** [comment]
Thanks! It was on my list to add this stuff .. or just overload the global
notification? You cant be started from both...  I hadnt decided.

**Comment by slycoder** [comment]
Happy to go with whichever approach seems the most reasonable to you; just lemme know.

In the meantime I added a bit more functionality (clearing of notifications).

**Comment by jacobrosenthal** [comment]
Finally getting around to trying this out. Im scheduling and presenting a notification and didReceiveLocalNotification is never called for me in RCTPushNotificationManager, but is called I put didReceiveLocalNotification in AppDelegate. Any ideas whats different?

**Comment by strefethen** [comment]
@jacobrosenthal  is this something you're considering submitting a PR to facebook/react-native?

**Comment by slycoder** [comment]
@jacobrosenthal Lemme put together a little hello world app so I can demo it end-to-end.

Is this gonna get rolled into the other open PR? I'll let you guys decide the best way to stage these merges.

**Comment by strefethen** [comment]
@slycoder were you planning on creating a PR for FB/react-native repo for this? Would love to see this pushed to the main repo.

**Comment by jacobrosenthal** [comment]
@strefethen I was going to confirm the operation and merge to mine. I wasnt able to get these additions working in my project yet though. Feel free to +1 the existing PR https://github.com/facebook/react-native/pull/1616 to get it some attention.

**Comment by slycoder** [comment]
@jacobrosenthal  I created a repo with a simple demo app, lemme know if it works for you:

https://github.com/slycoder/LocalNotificationsDemo

In particular, this commit gets the Xcode scaffolding in place:
https://github.com/slycoder/LocalNotificationsDemo/commit/8994ddd35c3333ce7906eea7750de475da5e44f7

And this commit does the modifications for the demo itself:
https://github.com/slycoder/LocalNotificationsDemo/commit/cd6b994a9f40c0c0b84d5ec6ed36f3028ae760bd

Just hit a button and 10 seconds later you'll get a notification event and the text field will be updated.

**Comment by randomer** [comment]
It didn't work for me: first it said that a bunch of libraries were missing, but when I copied them over, it said "No known class method for selector 'application:didReceiveLocalNotification:'"

**Comment by slycoder** [comment]
@randomer , which libraries were missing?

**Comment by randomer** [comment]
@slycoder The ones that reside in `node_modules/react-native/React/base` and also `"../../Libraries/PushNotificationIOS/RCTPushNotificationManager.h"`

**Comment by slycoder** [comment]
@randomer where did you end up copying them from?  Just trying to figure out if the paths need to be set up differently...

**Comment by jacobrosenthal** [comment]
They pulled my original request so if you want to PR to them directly now. Ill definitely try your example -- probably in next few days I have some free time, and then +1 your PR.

**Pull request closed without merging**
